DROP FUNCTION DATE_SUB(t in TIMESTAMP, i in INTERVAL);
DROP FUNCTION getTime();

DROP SEQUENCE SeqHid;
DROP SEQUENCE SeqPid;
DROP SEQUENCE SeqCid;
DROP SEQUENCE SeqGid;
DROP SEQUENCE SeqSid;
DROP SEQUENCE SeqTid;

DROP TABLE ReportTagData;
DROP TABLE Reports;
DROP TABLE Reads;
DROP TABLE UserTags;
DROP TABLE PostTags;
DROP TABLE Chats;
DROP TABLE PostVisibilities;
DROP TABLE Posts;
DROP TABLE ChatGroupMemberships;
DROP TABLE ChatGroups;
DROP TABLE Sessions;
DROP TABLE FriendRequests;
DROP TABLE Friendships;
DROP TABLE Users;
DROP TABLE Settings;
